/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PriceSchedule'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PriceSchedule'));
  } else {
    // Browser globals (root is window)
    if (!root.OrderCloud) {
      root.OrderCloud = {};
    }
    root.OrderCloud.BuyerProduct = factory(root.OrderCloud.ApiClient, root.OrderCloud.PriceSchedule);
  }
}(this, function(ApiClient, PriceSchedule) {
  'use strict';




  /**
   * The BuyerProduct model module.
   * @module model/BuyerProduct
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>BuyerProduct</code>.
   * @alias module:model/BuyerProduct
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>BuyerProduct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BuyerProduct} obj Optional instance to populate.
   * @return {module:model/BuyerProduct} The populated <code>BuyerProduct</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ReplenishmentPriceSchedule')) {
        obj['ReplenishmentPriceSchedule'] = PriceSchedule.constructFromObject(data['ReplenishmentPriceSchedule']);
      }
      if (data.hasOwnProperty('StandardPriceSchedule')) {
        obj['StandardPriceSchedule'] = PriceSchedule.constructFromObject(data['StandardPriceSchedule']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PriceSchedule} ReplenishmentPriceSchedule
   */
  exports.prototype['ReplenishmentPriceSchedule'] = undefined;
  /**
   * @member {module:model/PriceSchedule} StandardPriceSchedule
   */
  exports.prototype['StandardPriceSchedule'] = undefined;



  return exports;
}));


