/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['Sdk', 'model/Order'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../Sdk'), require('./Order'));
  } else {
    // Browser globals (root is window)
    if (!root.OrderCloud) {
      root.OrderCloud = {};
    }
    root.OrderCloud.OrderSplitResult = factory(root.OrderCloud.Sdk, root.OrderCloud.Order);
  }
}(this, function(Sdk, Order) {
  'use strict';




  /**
   * The OrderSplitResult model module.
   * @module model/OrderSplitResult
   */

  /**
   * Constructs a new <code>OrderSplitResult</code>.
   * @alias module:model/OrderSplitResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>OrderSplitResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderSplitResult} obj Optional instance to populate.
   * @return {module:model/OrderSplitResult} The populated <code>OrderSplitResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('OutgoingOrders')) {
        obj['OutgoingOrders'] = Sdk.convertToType(data['OutgoingOrders'], [Order]);
      }
      if (data.hasOwnProperty('RemainingLineItemIDs')) {
        obj['RemainingLineItemIDs'] = Sdk.convertToType(data['RemainingLineItemIDs'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Order>} OutgoingOrders
   */
  exports.prototype['OutgoingOrders'] = undefined;
  /**
   * @member {Array.<String>} RemainingLineItemIDs
   */
  exports.prototype['RemainingLineItemIDs'] = undefined;



  return exports;
}));


