/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OrderCloud) {
      root.OrderCloud = {};
    }
    root.OrderCloud.WebHook = factory(root.OrderCloud.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The WebHook model module.
   * @module model/WebHook
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WebHook</code>.
   * @alias module:model/WebHook
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>WebHook</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebHook} obj Optional instance to populate.
   * @return {module:model/WebHook} The populated <code>WebHook</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ID')) {
        obj['ID'] = ApiClient.convertToType(data['ID'], 'Number');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('Type')) {
        obj['Type'] = ApiClient.convertToType(data['Type'], 'String');
      }
      if (data.hasOwnProperty('Description')) {
        obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
      }
      if (data.hasOwnProperty('BaseUrl')) {
        obj['BaseUrl'] = ApiClient.convertToType(data['BaseUrl'], 'String');
      }
      if (data.hasOwnProperty('SharedKey')) {
        obj['SharedKey'] = ApiClient.convertToType(data['SharedKey'], 'String');
      }
      if (data.hasOwnProperty('AppendRoute')) {
        obj['AppendRoute'] = ApiClient.convertToType(data['AppendRoute'], 'Boolean');
      }
      if (data.hasOwnProperty('UseVerb')) {
        obj['UseVerb'] = ApiClient.convertToType(data['UseVerb'], 'Boolean');
      }
      if (data.hasOwnProperty('ElevatedClaimsList')) {
        obj['ElevatedClaimsList'] = ApiClient.convertToType(data['ElevatedClaimsList'], 'String');
      }
      if (data.hasOwnProperty('ConfigData')) {
        obj['ConfigData'] = ApiClient.convertToType(data['ConfigData'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Number} ID
   */
  exports.prototype['ID'] = undefined;
  /**
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * @member {String} Type
   */
  exports.prototype['Type'] = undefined;
  /**
   * @member {String} Description
   */
  exports.prototype['Description'] = undefined;
  /**
   * @member {String} BaseUrl
   */
  exports.prototype['BaseUrl'] = undefined;
  /**
   * @member {String} SharedKey
   */
  exports.prototype['SharedKey'] = undefined;
  /**
   * @member {Boolean} AppendRoute
   */
  exports.prototype['AppendRoute'] = undefined;
  /**
   * @member {Boolean} UseVerb
   */
  exports.prototype['UseVerb'] = undefined;
  /**
   * @member {String} ElevatedClaimsList
   */
  exports.prototype['ElevatedClaimsList'] = undefined;
  /**
   * @member {Object} ConfigData
   */
  exports.prototype['ConfigData'] = undefined;



  return exports;
}));


