/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.OpenIdConnect();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OpenIdConnect', function() {
    it('should create an instance of OpenIdConnect', function() {
      // uncomment below and update the code to test OpenIdConnect
      //var instane = new OrderCloud.OpenIdConnect();
      //expect(instance).to.be.a(OrderCloud.OpenIdConnect);
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instane = new OrderCloud.OpenIdConnect();
      //expect(instance).to.be();
    });

    it('should have the property stateHashKey (base name: "StateHashKey")', function() {
      // uncomment below and update the code to test the property stateHashKey
      //var instane = new OrderCloud.OpenIdConnect();
      //expect(instance).to.be();
    });

    it('should have the property orderCloudApiClientID (base name: "OrderCloudApiClientID")', function() {
      // uncomment below and update the code to test the property orderCloudApiClientID
      //var instane = new OrderCloud.OpenIdConnect();
      //expect(instance).to.be();
    });

    it('should have the property connectClientID (base name: "ConnectClientID")', function() {
      // uncomment below and update the code to test the property connectClientID
      //var instane = new OrderCloud.OpenIdConnect();
      //expect(instance).to.be();
    });

    it('should have the property connectClientSecret (base name: "ConnectClientSecret")', function() {
      // uncomment below and update the code to test the property connectClientSecret
      //var instane = new OrderCloud.OpenIdConnect();
      //expect(instance).to.be();
    });

    it('should have the property appStartUrl (base name: "AppStartUrl")', function() {
      // uncomment below and update the code to test the property appStartUrl
      //var instane = new OrderCloud.OpenIdConnect();
      //expect(instance).to.be();
    });

    it('should have the property authorizationEndpoint (base name: "AuthorizationEndpoint")', function() {
      // uncomment below and update the code to test the property authorizationEndpoint
      //var instane = new OrderCloud.OpenIdConnect();
      //expect(instance).to.be();
    });

    it('should have the property tokenEndpoint (base name: "TokenEndpoint")', function() {
      // uncomment below and update the code to test the property tokenEndpoint
      //var instane = new OrderCloud.OpenIdConnect();
      //expect(instance).to.be();
    });

  });

}));
