/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.PartialSpendingAccount();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PartialSpendingAccount', function() {
    it('should create an instance of PartialSpendingAccount', function() {
      // uncomment below and update the code to test PartialSpendingAccount
      //var instane = new OrderCloud.PartialSpendingAccount();
      //expect(instance).to.be.a(OrderCloud.PartialSpendingAccount);
    });

    it('should have the property ID (base name: "ID")', function() {
      // uncomment below and update the code to test the property ID
      //var instane = new OrderCloud.PartialSpendingAccount();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new OrderCloud.PartialSpendingAccount();
      //expect(instance).to.be();
    });

    it('should have the property balance (base name: "Balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instane = new OrderCloud.PartialSpendingAccount();
      //expect(instance).to.be();
    });

    it('should have the property allowAsPaymentMethod (base name: "AllowAsPaymentMethod")', function() {
      // uncomment below and update the code to test the property allowAsPaymentMethod
      //var instane = new OrderCloud.PartialSpendingAccount();
      //expect(instance).to.be();
    });

    it('should have the property redemptionCode (base name: "RedemptionCode")', function() {
      // uncomment below and update the code to test the property redemptionCode
      //var instane = new OrderCloud.PartialSpendingAccount();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "StartDate")', function() {
      // uncomment below and update the code to test the property startDate
      //var instane = new OrderCloud.PartialSpendingAccount();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "EndDate")', function() {
      // uncomment below and update the code to test the property endDate
      //var instane = new OrderCloud.PartialSpendingAccount();
      //expect(instance).to.be();
    });

    it('should have the property xp (base name: "xp")', function() {
      // uncomment below and update the code to test the property xp
      //var instane = new OrderCloud.PartialSpendingAccount();
      //expect(instance).to.be();
    });

  });

}));
