/**
 * OrderCloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: ordercloud@four51.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OrderCloud);
  }
}(this, function(expect, OrderCloud) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OrderCloud.StripeCreditCard();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StripeCreditCard', function() {
    it('should create an instance of StripeCreditCard', function() {
      // uncomment below and update the code to test StripeCreditCard
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be.a(OrderCloud.StripeCreditCard);
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

    it('should have the property _number (base name: "Number")', function() {
      // uncomment below and update the code to test the property _number
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

    it('should have the property expirationMonth (base name: "ExpirationMonth")', function() {
      // uncomment below and update the code to test the property expirationMonth
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

    it('should have the property expirationYear (base name: "ExpirationYear")', function() {
      // uncomment below and update the code to test the property expirationYear
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

    it('should have the property cvc (base name: "Cvc")', function() {
      // uncomment below and update the code to test the property cvc
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

    it('should have the property addressLine1 (base name: "AddressLine1")', function() {
      // uncomment below and update the code to test the property addressLine1
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

    it('should have the property addressLine2 (base name: "AddressLine2")', function() {
      // uncomment below and update the code to test the property addressLine2
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

    it('should have the property addressCity (base name: "AddressCity")', function() {
      // uncomment below and update the code to test the property addressCity
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

    it('should have the property addressState (base name: "AddressState")', function() {
      // uncomment below and update the code to test the property addressState
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

    it('should have the property addressZip (base name: "AddressZip")', function() {
      // uncomment below and update the code to test the property addressZip
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

    it('should have the property addressCountry (base name: "AddressCountry")', function() {
      // uncomment below and update the code to test the property addressCountry
      //var instane = new OrderCloud.StripeCreditCard();
      //expect(instance).to.be();
    });

  });

}));
