
export type ApiRole = 'ApiClientAdmin' | 
'ApiClientReader' | 
'AddressAdmin' | 
'AddressReader' | 
'AdminAddressAdmin' | 
'AdminAddressReader' | 
'AdminUserAdmin' | 
'AdminUserGroupAdmin' | 
'AdminUserGroupReader' | 
'AdminUserReader' | 
'ApprovalRuleAdmin' | 
'ApprovalRuleReader' | 
'BundleAdmin' | 
'BundleAssignmentAdmin' | 
'BundleReader' | 
'BuyerAdmin' | 
'BuyerImpersonation' | 
'BuyerReader' | 
'BuyerUserAdmin' | 
'BuyerUserReader' | 
'CatalogAdmin' | 
'CatalogReader' | 
'CategoryAdmin' | 
'CategoryReader' | 
'CostCenterAdmin' | 
'CostCenterReader' | 
'CreditCardAdmin' | 
'CreditCardReader' | 
'EntitySyncConfigAdmin' | 
'FullAccess' | 
'IncrementorAdmin' | 
'IncrementorReader' | 
'LocaleReader' | 
'LocaleAdmin' | 
'MeAddressAdmin' | 
'MeAdmin' | 
'MeCreditCardAdmin' | 
'MessageConfigAssignmentAdmin' | 
'MeSubscriptionAdmin' | 
'MeXpAdmin' | 
'OrderAdmin' | 
'OrderReader' | 
'OverrideShipping' | 
'OverrideTax' | 
'OverrideUnitPrice' | 
'PasswordReset' | 
'PriceScheduleAdmin' | 
'PriceScheduleReader' | 
'ProductAdmin' | 
'ProductAssignmentAdmin' | 
'ProductCollectionReader' | 
'ProductFacetAdmin' | 
'ProductFacetReader' | 
'ProductReader' | 
'ProductSyncConfigAdmin' | 
'PromotionAdmin' | 
'PromotionReader' | 
'SecurityProfileAdmin' | 
'SecurityProfileReader' | 
'SetSecurityProfile' | 
'ShipmentAdmin' | 
'ShipmentReader' | 
'Shopper' | 
'SpendingAccountAdmin' | 
'SpendingAccountReader' | 
'SubscriptionAdmin' | 
'SubscriptionReader' | 
'SupplierAddressAdmin' | 
'SupplierAddressReader' | 
'SupplierAdmin' | 
'SupplierReader' | 
'SupplierUserAdmin' | 
'SupplierUserGroupAdmin' | 
'SupplierUserGroupReader' | 
'SupplierUserReader' | 
'UnsubmittedOrderReader' | 
'UserGroupAdmin' | 
'UserGroupReader' | 
'OpenIDConnectReader' | 
'OpenIDConnectAdmin' | 
'MessageSenderReader' | 
'MessageSenderAdmin' | 
'XpIndexAdmin' | 
'WebhookReader' | 
'WebhookAdmin' | 
'IntegrationEventReader' | 
'IntegrationEventAdmin' | 
'TrackingEventReader' | 
'TrackingEventAdmin' | 
'DeliveryConfigAdmin' | 
'OrderSyncConfigAdmin' | 
'ErrorConfigAdmin'
